# -*- mode: Python -*-

k8s_yaml("k8s.yaml")
k8s_resource("nextjs-app", port_forwards=3000)

docker_build(
    "nextjs-app-image",
    context=".",
    dockerfile="Dockerfile.dev",
    live_update=[
        sync(".", "/app"),
        run(
            "bun install",
            trigger=["package.json"]
        )
    ]
)